select t.install_time date, datediff(w.timedate,t.install_time) retentionDay, t.client client,t.install_confversion confversion, count(distinct w.id) retentionUser from 
(select distinct id,client,install_confversion,to_date(from_unixtime(install_time)) install_time from hive_track_diagon.track_user where datesub='2015-08-24' and install_time>=unix_timestamp('2015-02-10 00:00:00') and install_time<unix_timestamp('2015-08-25 00:00:00')) t
join
(select distinct id,timedate from hive_track_diagon.log_track_diagon where datesub>='2015-08-09'  and action='login' ) w
on t.id=w.id
where datediff(w.timedate,t.install_time)>=0 
group by t.install_time,datediff(w.timedate,t.install_time),t.client,t.install_confversion;