select to_date(w.timedate) date,t.client client,t.install_confversion confversion, count(distinct w.id) payCount, sum(v3) payMoney 
from 
(select distinct id,client,install_confversion from hive_track_diagon.track_user where datesub='2015-08-24') t 
join 
(select id,timedate,v3 from hive_track_diagon.log_track_diagon where datesub>='2015-08-16' and action='pay') w 
on t.id=w.id group by to_date(w.timedate),t.client,t.install_confversion;