select to_date(w.timedate) date,t.client client,t.install_confversion confversion, count(distinct w.id) dau from 
(select distinct id,client,install_confversion from hive_track_diagon.track_user where datesub='2015-08-19' and install_time>=unix_timestamp('2015-08-16 00:00:00')) t 
join 
(select distinct id,timedate from hive_track_diagon.log_track_diagon where datesub>='2015-08-16' and action='login') w 
on t.id=w.id group by to_date(w.timedate),t.client,t.install_confversion;